import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { EditModeProvider } from "@/contexts/edit-mode-context";
import { PageLoadingProvider } from "@/contexts/page-loading-context";
import { EditModeLoading } from "@/components/edit-mode-loading";
import { PageLoading } from "@/components/page-loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PageLoadingProvider>
            <EditModeProvider>
              {children}
              <EditModeLoading />
              <PageLoading />
            </EditModeProvider>
          </PageLoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
